format = '$all'

[git_branch]
symbol = ""
style = "bold purple"
format = "on [$symbol $branch]($style) "

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = "󰁝"
behind = "󰁅"
diverged = "!"
untracked = "*"
modified = "~"
deleted = "-"
staged = "+"
conflicted = ""
style = "white"
format = '([\[$ahead_behind$all_status\]]($style))'