format = '$all'

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ï•"
behind = "ï•…"
diverged = "ï•…ï•"
untracked = "*"
stashed = "st "
modified = "Ã—"
staged = "+"
renamed = "~"
deleted = "-"
style = "bold "
format = '([\[$all_status$ahead_behind\]]($style))'
